### ISSUE TITLE
EDSC-2898: Cannot remove filter from granule search box

### ISSUE THREAD

**Issue by mreese84** [nasa/earthdata-search#1226]
### Description
Cannot remove search from granule search box. Deleting text and hitting 'Enter' causes the page to reload with the text re-populated.

**Reproduction Steps**

1. Visit https://search.uat.earthdata.nasa.gov/search/granules?p=C447308-ORNL_DAAC&pg[0][gsk]=-start_date&tl=1585761296!4!!
2. Copy/paste "1860_1993_2050_NITROGEN.N-deposition2050.txt" into the granule search field
3. Observe that only a single granule is returned
4. Delete the text in the granule search field and press enter
5. Observe that the page refreshed, the text just deleted remains, and only a single granule is returned

### Acceptance Criteria

1. Load any collection with granules
2. Copy/paste any of the granule titles into the search field and observe that the filter works as intended
3. Remove the granule search text and observe that no granule filter/search is applied and all expected granules return

**Comment by ManiacalBilby** [comment]
Going to look into this.

**Comment by heykc** [comment]
I can cover this issue! Setting up a draft PR in a few ✌️

**Comment by mreese84** [comment]
Awesome! Thank you @heykc

**Comment by abbottry** [comment]
Please make sure that you're running the tests (`npm run test` is the command, you can find other information in the readme) -- your PR has a failing test on some of the changes you made.

**Comment by heykc** [comment]
@abbottry apologies for not running the tests before pushing! I do have a question for you or anyone that would be able to answer. The test directly checks that props.onApplyGranuleFilters is called with `{ readableGranuleName: null }` however my change directly affects what we're sending to props.onApplyGranuleFilters (sending an empty array rather than null). Obviously I don't want to just change the test so that it passes with my fix, but correct me if I'm wrong, I do believe we should be passing in an empty array rather than a null value. 

If we pass a null value, we remove the null filter completely once the prunedFilters reducer runs inside of collections.js (line 116 in `\static\src\js\actions\collections.js` . Unless we somehow retain and pass the null filter to the UPDATE_GRANULE_SEARCH_QUERY action, we won't be able to update the state in Redux with the updated readableGranuleName value. And since an empty array is still truthy, we wouldn't be removing it in the prunedFilters reducer.

Let me know if you agree. If you do, I can make the change to the test file to expect an empty array, otherwise, I'm happy to discuss possible other actions we can take. ✌️
